from tadv.llm.langchain.prompts.sequential_gx._prompt import (
    COLUMN_ACCESS_DETECTION_PROMPT,
    CODE_GENERATION_PROMPT,
    SYSTEM_TASK_DESCRIPTION,
    ASSUMPTIONS_EXTRACTION_PROMPT as DEFAULT_ASSUMPTIONS_PROMPT,
)
