from inspect import cleandoc

SYSTEM_TASK_DESCRIPTION = cleandoc("""Task-aware data validation aims to generate data validation constraints on the dataset where the downstream task is run. "Task" here refers to the downstream code. The system should generate effective and efficient constraints on the data.
*Effective*: The constraints should reflect whether the data is harmful to the downstream code. Constraints should fail if the data is harmful to the downstream code. Additionally, the constraints should be precise to reduce false positive alerts, meaning the constraints should not fail if the data is not harmful to the downstream task.
*Efficient*: The constraints should only be applied to columns accessed by the code. Constraints on unused columns would lead to redundant calculations and false positive alerts.

The task-aware data validation system consists of the following components:
1. *Column Access Detection*:
Input: 
    Statistics of the columns in the dataset.
    Downstream code snippet.
Output:
    Columns accessed by the downstream code snippet.
Given a dataset and the downstream code, this component finds the columns that are used in the code snippet. These columns are the accessed columns for the downstream task.
2. *Assumptions Extraction*:
Input:
    Statistics of the columns in the dataset.
    Columns accessed by the downstream code snippet.
    Downstream code snippet.
Output:
    User's assumptions about the accessed columns.
Given the accessed columns, the dataset statistics, and the downstream code, this component extracts the code's assumptions and requirements about the accessed columns. These assumptions are used to generate executable validation rules, ensuring the data meets the user's expectations.
3. *Rule Generation*:
Input:
    Statistics of the columns in the dataset.
    Columns accessed by the downstream code snippet.
    Code's assumptions about the accessed columns.
    Downstream code snippet.
Output:
    Validation rules in Great Expectations format.
Given a dataset described by name, columns with corresponding downstream code, the accessed columns and the user's assumptions. This component converts the code's assumptions and requirements into formal validation rules to ensure the data meets the code's expectations. The rules are generated in Great Expectations format.
""")

COLUMN_ACCESS_DETECTION_PROMPT = cleandoc("""You are part of the task-aware data validation system. You serve as the *Column Access Detection* component.
Given a dataset and the downstream code, you are asked to find the columns that are used in the code snippet. These columns are the accessed columns for the downstream task to ensure that the constraints are only applied to accessed columns.

The dataset is a CSV file with the following columns:
{columns_desc}

The user writes the code snippet below:
{code_snippet}

The above code snippet is used for the following downstream task:
{downstream_task_description}

Your response should be a list of comma separated values
eg: `foo, bar, baz` or `foo,bar,baz`
""")

ASSUMPTIONS_EXTRACTION_PROMPT = cleandoc("""You are part of a task-aware data validation system. You serve as the *Assumptions Extraction* component.
Given that the code written for the downstream task may be not robust enough to handle all possible data scenarios, you should find the code's assumptions and requirements about the accessed columns. These assumptions would then be used to generate validation rules to ensure the data meets the code's expectations and requirements.


Here are the things you need to consider:
1. Make sure the assumptions are only about the accessed columns generated by the *Column Access Detection* component.
2. You can generate assumptions for both individual columns, i.e., the column named 'age' should be greater than 18, and relationships between columns, i.e., the column named 'age' should be greater than the column named 'min_age'.
3. The assumptions should be in a human-readable format and would be converted into formal validation rules in the next step.

The dataset is a CSV file with the following columns:
{columns_desc}

The user writes the code snippet below:
{code_snippet}

The accessed columns generated by the *Column Access Detection* component are:
{accessed_columns}

The above code snippet is used for the following downstream task:
{downstream_task_description}

Please generate the assumptions as a JSON object with the column names as keys and a list of assumptions in natural language as values.
e.g., ```{{'column_name_1': ['assumption_1', 'assumption_2', ...], 'column_name_2': ['assumption_1', 'assumption_2', ...], ...}}```
""")

# https://greatexpectations.io/expectations/
CODE_GENERATION_PROMPT = cleandoc("""You are part of a task-aware data validation system. You serve as the *Rule Generation* component.
You are asked to transform the code's assumptions into formal validation rules to ensure the data meets the user's assumptions and requirements. The rules should be generated in Great Expectations format.

The function signature for Great Expectations constraints is as follows:
```
{expectations_text_descriptions}
```
To help you understand the signature, here are some examples:

ExpectColumnMeanToBeBetween(column="test",min_value=1,max_value=3)
ExpectColumnMinToBeBetween(column="test",min_value=.5,max_value=1)
ExpectColumnPairValuesAToBeGreaterThanB(column_A="test2",column_B="test")
ExpectColumnSumToBeBetween(column="test2",min_value=2,max_value=6)
ExpectColumnUniqueValueCountToBeBetween(column="test2",min_value=3,max_value=5)
ExpectColumnValuesToBeBetween(column="test",min_value=.5,max_value=2)
ExpectColumnValuesToMatchRegexList(column="test2",regex_list=["^a.*", "^b.*"],match_on="any")

The user writes the code snippet below:
{code_snippet}

The above code snippet is used for the following downstream task:
```
{downstream_task_description}
```
The accessed columns generated by the *Column Access Detection* component are:
```
{accessed_columns}
```

The Intuitions generated by the *Assumption Extraction* component are:
```
{assumptions}
```

Please generate validation rules as a JSON object with the column names as keys and a list of assumptions as values.
e.g., ```
{{
    "column_name_1": ["gx_expectation_1", "gx_expectation_2", ...],
    "column_name_2": ["gx_expectation_1", "gx_expectation_2", ...],
    ...
}}```
The gx_expectation_1, gx_expectation_2, above should be replaced with the actual Great Expectations function signature.
""")
