- MissingCategoricalValueCorruption:
    Columns:
    - Medical Condition
    Params:
      severity: 0.1
      sampling: CAR
      max_unique_num: 30
      corrupt_strategy: to_majority
- MissingCategoricalValueCorruption:
    Columns:
    - Admission Type
    Params:
      severity: 0.1
      sampling: CAR
      max_unique_num: 30
      corrupt_strategy: to_majority
- GaussianNoise:
    Columns:
    - Age
    Params:
      severity: 0.2
      sampling: CAR
