- GaussianNoise:
    Columns:
    - Age
    Params:
      severity: 0.3
      sampling: CAR
- ColumnInserting:
    Columns:
    - Name
    Params:
      severity: 1
      sampling: CAR
      corrupt_strategy: add_prefix
