- Scaling:
    Columns:
    - loan_amnt
    Params:
      severity: 0.3
      sampling: CAR
- MissingCategoricalValueCorruption:
    Columns:
    - person_home_ownership
    Params:
      severity: 0.1
      sampling: CAR
      max_unique_num: 30
      corrupt_strategy: to_majority
