- Scaling:
    Columns:
    - loan_amnt
    Params:
      severity: 0.3
      sampling: CAR
- MissingCategoricalValueCorruption:
    Columns:
    - person_home_ownership
    Params:
      severity: 0.1
      sampling: CAR
      max_unique_num: 30
      corrupt_strategy: to_nan
- MissingCategoricalValueCorruption:
    Columns:
    - cb_person_default_on_file
    Params:
      severity: 0.1
      sampling: CAR
      max_unique_num: 30
      corrupt_strategy: to_random
- GaussianNoise:
    Columns:
    - person_emp_length
    Params:
      severity: 0.2
      sampling: CAR
- ColumnInserting:
    Columns:
    - loan_intent
    Params:
      severity: 0.1
      sampling: CAR
      corrupt_strategy: add_prefix
- ColumnInserting:
    Columns:
    - person_home_ownership
    - person_age
    Params:
      severity: 0.1
      sampling: CAR
      corrupt_strategy: concatenate
