- MaskValues:
    Columns:
    - Doctor
    Params:
      severity: 0.3
      sampling: CAR
- MissingCategoricalValueCorruption:
    Columns:
    - Admission Type
    Params:
      severity: 0.1
      sampling: CAR
      max_unique_num: 30
      corrupt_strategy: to_majority
