SYSTEM_TASK_DESCRIPTION = """The system is designed to generate context-aware validation rules for a dataset which is used for multiple downstream tasks including machine learning pipeline, data analysis, business intelligence, etc. Context-aware means that the system should be able to understand the user's intuitions and generate validation rules that meet the user's expectations to ensure the data meets the user's expectations.

The system contains the following components:
1. *Relevant Column Target*: Given a dataset described by name, columns with corresponding downstream code. This component finds the columns that are used in the code snippet.
2. *Expectation Extraction*: Given a dataset described by name, columns with corresponding downstream code and the relevant columns. This component generates user's assumptions about these columns.
3. *Rule Generation*: Given a dataset described by name, columns with corresponding downstream code, the relevant columns and the user's assumptions. This component generates formal validation rules for the dataset.
"""

RELEVENT_COLUMN_TARGET_PROMPT = """You are part of a context-aware data validation system.
You serve as the *Relevant Column Target* component. You are asked to find the columns used in the code snippet.
The dataset is a CSV file with the following columns:
{columns}

The user writes the code snippet below:
{code_snippet}

Please generate the columns that are used in the code snippet in the following format:
```['column_name_1', 'column_name_2', ...]```
"""

EXPECTATION_EXTRACTION_PROMPT = """You are part of a context-aware data validation system.
Given that the user may not have a complete understanding of the dataset, you should find the user's intuitions. These intuitions would then be used to generate validation rules to ensure the data meets the user's expectations.


Here are the things you need to consider:
1. Make sure the assumptions are only about the relevant columns generated by the *Relevant Column Target* component.
2. You can generate assumptions for both individual columns and relationships between columns.
3. The assumptions should be in a human-readable format.

The dataset is a CSV file with the following columns:
{columns}

The user writes the code snippet below:

{code_snippet}

The relevant columns generated by the *Relevant Column Target* component are:
{relevant_columns}

Please generate validation rules for the dataset in the following format:
```{{'column_name_1': ['assumption_1', 'assumption_2', ...], 'column_name_2': ['assumption_1', 'assumption_2', ...], ...}}```
"""

RULE_GENERATION_PROMPT = """You are part of a context-aware data validation system. {SYSTEM_TASK_DESCRIPTION} You are asked to transform the user's intuitions into formal validation rules to ensure the data meets the user's expectations. We are using PyDeequ as the validation library so the rules should be in PyDeequ format.

"""
