- ColumnInserting:
    Columns:
    - Hospital
    Params:
      severity: 1
      sampling: CAR
      corrupt_strategy: sanitize_to_identifier
- ColumnDropping:
    Columns:
    - Date of Admission
    Params:
      severity: 1
      sampling: CAR
