name: test_env
on: push
jobs:
    test_env:
        runs-on: ubuntu-latest
        steps:
        - name: Check GITHUB_TOKEN
          run: echo "Codecov token starts with ${GITHUB_TOKEN:0:4}***"
          env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}